create or replace PROCEDURE SP_ALTERA_CURSO
                           (P_CD_CURSO CURSO.CD_CURSO%TYPE,
                            P_NM_CURSO CURSO.NM_CURSO%TYPE,
                            P_DT_INICIO CURSO.DT_INICIO%TYPE,
                            P_DT_FIM CURSO.DT_FIM%TYPE,
                            P_FEEDBACK OUT VARCHAR2)
IS
   E_ERRO_NOME_CURSO EXCEPTION;
   E_ERRO_DATA_CURSO EXCEPTION;
BEGIN
   IF P_NM_CURSO IS NULL OR LENGTH(P_NM_CURSO) > 30 THEN
      RAISE E_ERRO_NOME_CURSO;
   END IF;
   IF P_DT_FIM < P_DT_INICIO THEN
      RAISE E_ERRO_DATA_CURSO;
   END IF;

   UPDATE CURSO 
      SET NM_CURSO  = P_NM_CURSO,
          DT_INICIO = P_DT_INICIO,
          DT_FIM    = P_DT_FIM
    WHERE CD_CURSO  = P_CD_CURSO;

   P_FEEDBACK := 'CURSO '||P_NM_CURSO||' ALTERADO COM SUCESSO!';

   EXCEPTION
      WHEN E_ERRO_NOME_CURSO THEN
         P_FEEDBACK := 'O NOME DO CURSO NÃO PODE SER NULO E DEVE CONTER'||
                              ' NO MÁXIMO 30 CARACTERES';
      WHEN E_ERRO_DATA_CURSO THEN
         P_FEEDBACK := 'A DATA DE FIM DEVE SER MAIOR QUE A DATA DE INICIO DO CURSO!';
END;