CREATE TABLE CURSO (
    COD_CURSO NUMBER(10) CONSTRAINT PK_CURSO PRIMARY KEY,
    NOM_CURSO VARCHAR2(30 CHAR) NOT NULL,
    DAT_INICIO DATE,
    DAT_FIM DATE,
    CONSTRAINT CK_DATA CHECK (DAT_FIM > DAT_INICIO));
    
CREATE TABLE ALUNO (
    COD_ALUNO NUMBER(10) CONSTRAINT PK_ALUNO PRIMARY KEY,
    NUM_MATRICULA VARCHAR2(10 CHAR) NOT NULL,
    NOM_ALUNO VARCHAR2(50 CHAR) NOT NULL,
    DAT_MATRICULA DATE DEFAULT SYSDATE,
    NOM_CIDADE VARCHAR2(40 CHAR) DEFAULT 'SAO PAULO',
    NUM_IDADE NUMBER(3)
         CONSTRAINT CK_MAIOR CHECK (NUM_IDADE >= 18),
    DES_EMAIL VARCHAR2(255) CONSTRAINT UK_EMAIL UNIQUE,
    COD_CURSO NUMBER(10)
         CONSTRAINT FK_CURSO REFERENCES CURSO(COD_CURSO),
    CONSTRAINT CK_EMAIL_MIN CHECK(LOWER(DES_EMAIL) = DES_EMAIL));
         
--EXEMPLO DE FK NO NIVEL DA TABELA   
CREATE TABLE ALUNO (
    COD_ALUNO NUMBER(10) CONSTRAINT PK_ALUNO PRIMARY KEY,
    NUM_MATRICULA VARCHAR2(10 CHAR) NOT NULL,
    NOM_ALUNO VARCHAR2(50 CHAR) NOT NULL,
    DAT_MATRICULA DATE DEFAULT SYSDATE,
    NOM_CIDADE VARCHAR2(40 CHAR) DEFAULT 'SAO PAULO',
    NUM_IDADE NUMBER(3)
         CONSTRAINT CK_MAIOR CHECK (NUM_IDADE >= 18),
    DES_EMAIL VARCHAR2(255) CONSTRAINT UK_EMAIL UNIQUE,
    COD_CURSO NUMBER(10),
    CONSTRAINT CK_EMAIL_MIN CHECK(LOWER(DES_EMAIL) = DES_EMAIL),
    CONSTRAINT FK_CURSO FOREIGN KEY (COD_CURSO)
               REFERENCES CURSO(COD_CURSO) ON DELETE CASCADE
    );   
   
INSERT INTO CURSO VALUES (
    97000, 'SQL FUNDAMENTOS',
    TO_DATE('07/03/2019', 'DD/MM/YYYY'),
    TO_DATE('09/04/2019', 'DD/MM/YYYY'));
    
INSERT INTO CURSO VALUES (
    97001, 'PL/SQL',
    TO_DATE('15/04/2019', 'DD/MM/YYYY'),
    TO_DATE('15/05/2019', 'DD/MM/YYYY'));
    
SELECT * FROM CURSO;   
   
INSERT INTO ALUNO (COD_ALUNO, NUM_MATRICULA, NOM_ALUNO, NUM_IDADE,
                   NOM_CIDADE, DES_EMAIL, COD_CURSO)
       VALUES (1, 'MAT00001', 'VICTOR SILVA BRUM', 25,
               DEFAULT, 'victor_b@gmail.com', 97001);
   
INSERT INTO ALUNO (COD_ALUNO, NUM_MATRICULA, NOM_ALUNO, NUM_IDADE,
                   NOM_CIDADE, DES_EMAIL, COD_CURSO)
       VALUES (2, 'MAT00002', 'MARCIA BARBOSA DA SILVA', 19,
               'BELO HORIZONTE', 'mbarbosasilva@gmail.com', 97000);
   
SELECT * FROM ALUNO;   
   
UPDATE ALUNO SET 
       NUM_IDADE = 17
 WHERE COD_ALUNO = 2;       
   
DELETE CURSO WHERE COD_CURSO = 97000;   

TRUNCATE TABLE CURSO;
   

CREATE TABLE ALUNO_COPIA
     AS SELECT * FROM ALUNO;

SELECT * FROM ALUNO_COPIA;


CREATE TABLE EMP_SAL_ANUAL AS
  SELECT EMPLOYEE_ID EMP_ID, FIRST_NAME NOME, SALARY SAL,
         SALARY * 12 SAL_ANUAL
     FROM EMPLOYEES;

SELECT * FROM EMP_SAL_ANUAL;

ALTER TABLE ALUNO
   ADD (NOM_UNIDADE VARCHAR2(5 CHAR));

SELECT * FROM ALUNO;   

ALTER TABLE ALUNO
   ADD (NOM_UNIDADE VARCHAR2(20 CHAR) DEFAULT 'MORUMBI' NOT NULL);
   
ALTER TABLE ALUNO
   DROP COLUMN NOM_UNIDADE;
   
SELECT * FROM ALUNO;

ALTER TABLE ALUNO
   MODIFY (NOM_UNIDADE VARCHAR2(3 CHAR));

ALTER TABLE ALUNO
   SET UNUSED (NOM_UNIDADE);
   
SELECT * FROM ALUNO;   

DESC ALUNO;

ALTER TABLE ALUNO
      DROP UNUSED COLUMNS;

-- USER_...
SELECT * FROM USER_TABLES;
-- ALL_...
SELECT * FROM ALL_TABLES;
--DBA_...
SELECT * FROM DBA_TABLES;

SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, CHAR_LENGTH,
       CHAR_USED
  FROM ALL_TAB_COLUMNS
 WHERE OWNER = 'ORA1'
   AND TABLE_NAME = 'ALUNO';

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION,
       R_CONSTRAINT_NAME, DELETE_RULE, STATUS
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME = 'ALUNO';


SELECT * FROM DICT;   
    
SELECT * FROM USER_OBJECTS;
    
SELECT * FROM USER_TAB_COMMENTS;

COMMENT ON TABLE CURSO IS 'Tabela com os cursos da Ka Solution';

DESC CURSO;

COMMENT ON COLUMN CURSO.COD_CURSO IS 'Código do curso';
COMMENT ON COLUMN CURSO.NOM_CURSO IS 'Nome do curso';
COMMENT ON COLUMN CURSO.DAT_INICIO IS 'Data de início do curso';
COMMENT ON COLUMN CURSO.DAT_FIM IS 'Data de fim (deve ser maior que a data de inicio)';

SELECT * FROM USER_COL_COMMENTS WHERE TABLE_NAME = 'CURSO';



    