--SEQUENCE/SINONIMOS E INDICES

CREATE SEQUENCE SEQ_COD_CURSO
      INCREMENT BY 1
      START WITH 98000;
      
CREATE SEQUENCE SEQ_COD_ALUNO
     INCREMENT BY 1
     START WITH 100;
     
SELECT SEQ_COD_CURSO.NEXTVAL FROM DUAL;     
SELECT SEQ_COD_CURSO.CURRVAL FROM DUAL;     

SELECT SEQ_COD_ALUNO.NEXTVAL FROM DUAL;
SELECT SEQ_COD_ALUNO.CURRVAL FROM DUAL;
      
ALTER TABLE CURSO MODIFY (
   COD_CURSO DEFAULT SEQ_COD_CURSO.NEXTVAL);

ALTER TABLE ALUNO MODIFY
   COD_ALUNO DEFAULT SEQ_COD_ALUNO.NEXTVAL;
   
   
INSERT INTO CURSO (NOM_CURSO, DAT_INICIO, DAT_FIM)
      VALUES ('SAP', SYSDATE, SYSDATE + 30);
SELECT * FROM CURSO;   

INSERT INTO ALUNO (COD_ALUNO, NUM_MATRICULA, NOM_ALUNO, NUM_IDADE,
                   DES_EMAIL, COD_CURSO)
           VALUES (DEFAULT, 'MA00103', 'SHAKIRA', 18,
                   'shakira@gmail.com', SEQ_COD_CURSO.CURRVAL);

SELECT * FROM ALUNO;
SELECT SEQ_COD_CURSO.CURRVAL FROM DUAL;
SELECT SEQ_COD_ALUNO.CURRVAL FROM DUAL;


ALTER SEQUENCE SEQ_COD_CURSO
     MAXVALUE 999000;

SELECT * FROM USER_SEQUENCES;

SELECT * FROM ORA41.EMPLOYEES;

SELECT * FROM DEPT;

CREATE SYNONYM DEPT FOR DEPARTMENTS;

SELECT * FROM ORA41EMP;

CREATE SYNONYM ORA41EMP FOR ORA41.EMPLOYEES;

SELECT * FROM USER_SYNONYMS;

SELECT *
  FROM ALUNO
 WHERE NOM_ALUNO LIKE 'CARLOS%';

CREATE INDEX IDX_NOMALUNO ON ALUNO(NOM_ALUNO);      

SELECT *
  FROM CURSO
 WHERE DAT_INICIO BETWEEN TO_DATE('01/01/2019') AND TO_DATE('01/05/2019')
   AND DAT_FIM    BETWEEN TO_DATE('02/05/2019') AND TO_DATE('31/12/2019');
 
CREATE INDEX IDX_DATACURSO ON CURSO(DAT_INICIO, DAT_FIM);

SELECT *
  FROM EMPLOYEES
 ORDER BY UPPER(FIRST_NAME);
 
 
CREATE INDEX IDX_FNAMEUPPER ON EMPLOYEES(UPPER(FIRST_NAME)); 
 
 
DESC ALUNO;


CREATE INDEX IDX_CDCURSO ON ALUNO(COD_CURSO);

SELECT TABLE_NAME, INDEX_NAME, C.COLUMN_NAME
  FROM USER_INDEXES I
  JOIN USER_IND_COLUMNS C USING(INDEX_NAME, TABLE_NAME)
 WHERE TABLE_NAME = 'ALUNO';
 
 
--VIEWS 
CREATE OR REPLACE VIEW EMP50 AS
    SELECT EMPLOYEE_ID EMP_ID, UPPER(FIRST_NAME) NOME,
           UPPER(LAST_NAME) SOBRENOME,
           TO_CHAR(HIRE_DATE, 'DD/MM/YYYY - DAY') DT_ADM,
           TO_CHAR(SALARY, 'fmL999g9990d00') SALARIO
      FROM ORA41EMP
     WHERE DEPARTMENT_ID = 50
     ORDER BY NOME;
     
     
SELECT * FROM EMP50;

SELECT * FROM USER_VIEWS WHERE VIEW_NAME = 'EMP50';

CREATE OR REPLACE VIEW EMP_80 AS
   SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME,
          EMAIL, HIRE_DATE, JOB_ID, DEPARTMENT_ID
     FROM EMPLOYEES
    WHERE DEPARTMENT_ID = 80
     WITH CHECK OPTION CONSTRAINT CK_EMP80; 
    
SELECT * FROM EMP_80;    
SELECT * FROM EMPLOYEES WHERE FIRST_NAME = 'Carlos'; 

INSERT INTO EMP_80 VALUES (EMPLOYEES_SEQ.NEXTVAL, 'Pablo', 'Vittar',
                           'VITTARP', SYSDATE, 'SA_REP', 50);
                           
CREATE OR REPLACE VIEW EMP_90 AS
   SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME,
          EMAIL, HIRE_DATE, JOB_ID, DEPARTMENT_ID
     FROM EMPLOYEES
    WHERE DEPARTMENT_ID = 90
  WITH READ ONLY CONSTRAINT RO_EMP90;    
    
SELECT * FROM EMP_90;
                           
                           
                          




