--UNION
SELECT JOB_ID, EMPLOYEE_ID, DEPARTMENT_ID  --A
  FROM JOB_HISTORY
 WHERE DEPARTMENT_ID IN (90, 80, 50)
UNION
SELECT TO_CHAR(HIRE_DATE), EMPLOYEE_ID, DEPARTMENT_ID  --B
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IN (90, 80, 50);
   
   
SELECT JOB_ID, EMPLOYEE_ID, DEPARTMENT_ID, 'NADA CONSTA'  --A
  FROM JOB_HISTORY
 WHERE DEPARTMENT_ID IN (90, 80, 50)
UNION
SELECT JOB_ID, EMPLOYEE_ID, DEPARTMENT_ID, FIRST_NAME  --B
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IN (90, 80, 50);   
 
--INTERSECT 
 
SELECT JOB_ID, EMPLOYEE_ID, DEPARTMENT_ID, HIRE_DATE --A
  FROM EMPLOYEES
INTERSECT
SELECT JOB_ID, EMPLOYEE_ID, DEPARTMENT_ID, END_DATE --B
  FROM JOB_HISTORY;
 
--MINUS
SELECT EMPLOYEE_ID, JOB_ID --A
  FROM EMPLOYEES
MINUS
SELECT EMPLOYEE_ID, JOB_ID --B
  FROM JOB_HISTORY;
 
 
SELECT E.EMPLOYEE_ID, E.FIRST_NAME
  FROM EMPLOYEES E JOIN (SELECT EMPLOYEE_ID       --A
                          FROM EMPLOYEES
                         MINUS
                         SELECT EMPLOYEE_ID       --B
                           FROM JOB_HISTORY) RM
                ON E.EMPLOYEE_ID = RM.EMPLOYEE_ID;
                
--UNION ALL                
                
SELECT JOB_ID
  FROM EMPLOYEES
UNION ALL
SELECT JOB_ID
  FROM JOB_HISTORY;
  
DESC DEPARTMENTS;  
   
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID)
                 VALUES (200, 'Database', null, null);

INSERT INTO DEPARTMENTS VALUES (210, 'Redes', null, null);

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME)
                VALUES (220, 'Suporte');

INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME)
                VALUES (&DEPT_ID, '&DEPT_NAME');

SELECT * FROM DEPARTMENTS;   

CREATE TABLE EMP_TEMP (
     EMP_ID      NUMBER(10)         PRIMARY KEY,
     EMP_NAME    VARCHAR2(50 CHAR)  NOT NULL,
     EMP_SAL     NUMBER(8,2)        NOT NULL);


INSERT INTO EMP_TEMP (EMP_ID, EMP_NAME, EMP_SAL)
            SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
              FROM EMPLOYEES
             WHERE DEPARTMENT_ID IN (50,60);

SELECT * FROM EMP_TEMP;

SELECT * FROM EMP_TEMP
 WHERE EMP_ID BETWEEN 141 AND 144;
 
UPDATE EMP_TEMP SET
       EMP_SAL = EMP_SAL * 1.10,
       EMP_NAME = EMP_NAME || '**'
 WHERE EMP_ID NOT BETWEEN 141 AND 144;

SELECT * FROM EMP_TEMP;


DELETE EMP_TEMP WHERE EMP_ID > 300;

DELETE DEPARTMENTS WHERE DEPARTMENT_ID >= 200;


-- FAZER COM QUE TODOS OS EMPREGADOS QUE POSSUEM O MESMO JOB_ID DO EMPREGADO 200
-- SEJAM TRANSFERIDOS PARA O DEPARTAMENTO DO EMPREGADO 100

UPDATE EMPLOYEES SET
       DEPARTMENT_ID = (SELECT DEPARTMENT_ID --90
                          FROM EMPLOYEES WHERE EMPLOYEE_ID = 100)
 WHERE JOB_ID = (SELECT JOB_ID --AD_ASST
                   FROM EMPLOYEES WHERE EMPLOYEE_ID = 200);

--DEVELOPER 1
UPDATE EMP_TEMP
       SET EMP_SAL = 12000
  WHERE EMP_ID = 144;
  
SELECT * FROM EMP_TEMP;  

--DEVELOPER 1
SELECT *
  FROM EMP_TEMP
 WHERE EMP_ID = 143
   FOR UPDATE;








   