-- INSTRUÇÃO WITH

WITH
 AVG_EMP AS
   (SELECT AVG(SALARY) MEDIA FROM EMPLOYEES),
 MIN_DPT AS
   (SELECT DEPARTMENT_ID, MIN(SALARY) MINSAL
      FROM EMPLOYEES
     GROUP BY DEPARTMENT_ID)
SELECT DEPARTMENT_ID, ROUND(MINSAL - MEDIA,2) DIFSAL
  FROM AVG_EMP, MIN_DPT;
  
--USUÁRIOS
--ARQUIVO MEU_USUARIO.SQL

CREATE TABLE SAL_LOW (
   EMP_ID NUMBER(10),
   NAME   VARCHAR2(30 CHAR),
   SALARY NUMBER(10,2));

CREATE TABLE SAL_MID (
   EMP_ID NUMBER(10),
   NAME   VARCHAR2(30 CHAR),
   SALARY NUMBER(10,2));

CREATE TABLE SAL_HIG (
   EMP_ID NUMBER(10),
   NAME   VARCHAR2(30 CHAR),
   SALARY NUMBER(10,2));

INSERT FIRST
   WHEN SALARY < 5000 THEN
      INTO SAL_LOW VALUES (EMPLOYEE_ID, FIRST_NAME, SALARY)
   WHEN SALARY < 10000 THEN
      INTO SAL_MID VALUES (EMPLOYEE_ID, FIRST_NAME, SALARY)
   ELSE 
      INTO SAL_HIG VALUES (EMPLOYEE_ID, FIRST_NAME, SALARY)

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY FROM EMPLOYEES;     

SELECT * FROM SAL_HIG;

CREATE TABLE SAL (
   EMPID NUMBER(10),
   HIREDATE DATE,
   SALARY NUMBER(10,2));
   
CREATE TABLE MGR (
   EMPID NUMBER(10),
   MGR NUMBER(10),
   JOBID VARCHAR2(10 CHAR));
   
INSERT ALL
  WHEN HIRE_DATE > TO_DATE('31/12/2006','DD/MM/YYYY') THEN
     INTO SAL VALUES (EMPLOYEE_ID, HIRE_DATE, SALARY)
  WHEN SALARY > 8000 THEN
     INTO MGR VALUES (EMPLOYEE_ID, MANAGER_ID, JOB_ID)
SELECT EMPLOYEE_ID, HIRE_DATE, MANAGER_ID, SALARY, JOB_ID
  FROM EMPLOYEES;
  
SELECT EMPID FROM SAL
INTERSECT
SELECT EMPID FROM MGR;

SELECT * FROM SAL;

--MERGE
CREATE TABLE COPY_EMP AS
  SELECT EMPLOYEE_ID EMPID,
         FIRST_NAME,
         SALARY,
         DEPARTMENT_ID
    FROM EMPLOYEES WHERE DEPARTMENT_ID = 50;

UPDATE COPY_EMP SET SALARY = 0;
COMMIT;
SELECT * FROM COPY_EMP;

MERGE INTO COPY_EMP "DESTINO"
USING (SELECT * FROM EMPLOYEES
        WHERE DEPARTMENT_ID IN (50,60)) "ORIGEM"
ON (DESTINO.EMPID = ORIGEM.EMPLOYEE_ID)
WHEN MATCHED THEN
   UPDATE SET DESTINO.SALARY = ORIGEM.SALARY
WHEN NOT MATCHED THEN
   INSERT VALUES (ORIGEM.EMPLOYEE_ID, ORIGEM.FIRST_NAME,
                  ORIGEM.SALARY, ORIGEM.DEPARTMENT_ID);   
                  
--INTERVALO DE TEMPO E DATA
SELECT EMPLOYEE_ID, FIRST_NAME,
       HIRE_DATE,
       HIRE_DATE + TO_YMINTERVAL('0-6') FERIAS
  FROM EMPLOYEES;       

SELECT
   TO_CHAR(SYSDATE + TO_DSINTERVAL('3 12:30:00'),
                          'DD/MM/YYYY HH24:MI:SS') NOVA_DATA
FROM DUAL;

SELECT EXTRACT(YEAR FROM SYSDATE) ANO FROM DUAL;
SELECT EXTRACT(MONTH FROM SYSDATE) MES FROM DUAL;
SELECT EXTRACT(DAY FROM SYSDATE) DIA FROM DUAL;
SELECT EXTRACT(HOUR FROM CURRENT_TIMESTAMP) HORA FROM DUAL;
SELECT EXTRACT(MINUTE FROM CURRENT_TIMESTAMP) MINUTO FROM DUAL;








                  
                  

   
   













  
  
  