SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID,
  CASE JOB_ID
     WHEN 'IT_PROG'  THEN '10%'
     WHEN 'ST_CLERK' THEN '15%'
     WHEN 'SA_REP'   THEN TO_CHAR(SALARY * 2)
     ELSE '0%'
  END GRATIFICAÇÃO
FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY,
       CASE
          WHEN SALARY < 5000 THEN 'BAIXO'
          WHEN SALARY < 10000 THEN 'MEDIO'
          WHEN SALARY < 20000 THEN 'ALTO'
          ELSE 'EXCELENTE'
        END NÍVEL_SALARIO
  FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID,
  DECODE(JOB_ID,
         'IT_PROG', '10%',
         'ST_CLERK','15%',
         'SA_REP',  '20%',
         '0%') GRATIFICAÇÃO
FROM EMPLOYEES;

SELECT MAX(SALARY), MIN(SALARY), SUM(SALARY), AVG(SALARY)
  FROM EMPLOYEES;
  
SELECT COUNT(*) FROM EMPLOYEES;
SELECT COUNT(COMMISSION_PCT) QTD_COMISS FROM EMPLOYEES;
SELECT COUNT(DISTINCT JOB_ID) FROM EMPLOYEES;

SELECT DEPARTMENT_ID, JOB_ID, ROUND(AVG(SALARY),2) MÉDIA
  FROM EMPLOYEES
 WHERE JOB_ID <> 'IT_PROG'
 GROUP BY DEPARTMENT_ID, JOB_ID
HAVING AVG(SALARY) >= 10000;

 
SELECT DEPARTMENT_ID, JOB_ID, ROUND(SUM(SALARY),2) SOMA_SALARIOS
  FROM EMPLOYEES
 WHERE HIRE_DATE <= TO_DATE('31/12/2007','DD/MM/YYYY')
 GROUP BY DEPARTMENT_ID, JOB_ID
 HAVING SUM(SALARY) > 15000;
 
 
SELECT MAX(AVG(SALARY)) 
  FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID; 
 
--CAPITULO 7
SELECT EMP.EMPLOYEE_ID ID,
       EMP.FIRST_NAME NOME,
       EMP.DEPARTMENT_ID ID_DEPT,
       DEPT.DEPARTMENT_NAME NOM_DEPT
  FROM EMPLOYEES EMP, DEPARTMENTS DEPT
 WHERE EMP.DEPARTMENT_ID = DEPT.DEPARTMENT_ID;

 
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.JOB_ID, J.JOB_TITLE
  FROM EMPLOYEES E, JOBS J
 WHERE E.JOB_ID = J.JOB_ID;
 
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.JOB_ID, J.JOB_TITLE
  FROM EMPLOYEES E JOIN JOBS J
       ON E.JOB_ID = J.JOB_ID;

SELECT EMP.EMPLOYEE_ID ID,
       EMP.FIRST_NAME NOME,
       EMP.DEPARTMENT_ID ID_DEPT,
       DEPT.DEPARTMENT_NAME NOM_DEPT,
       LOC.CITY
  FROM EMPLOYEES EMP JOIN DEPARTMENTS DEPT
       ON EMP.DEPARTMENT_ID = DEPT.DEPARTMENT_ID
  JOIN LOCATIONS LOC
       ON LOC.LOCATION_ID = DEPT.LOCATION_ID;
       


SELECT EMP.EMPLOYEE_ID ID,
       EMP.FIRST_NAME NOME,
       DEPARTMENT_ID ID_DEPT,
       DEPT.DEPARTMENT_NAME NOM_DEPT
  FROM EMPLOYEES EMP NATURAL JOIN DEPARTMENTS DEPT;
       
SELECT EMP.EMPLOYEE_ID ID,
       EMP.FIRST_NAME NOME,
       DEPARTMENT_ID ID_DEPT,
       DEPT.DEPARTMENT_NAME NOM_DEPT,
       LOC.CITY
  FROM EMPLOYEES EMP JOIN DEPARTMENTS DEPT USING(DEPARTMENT_ID, MANAGER_ID)
       NATURAL JOIN LOCATIONS LOC;
       

SELECT E.EMPLOYEE_ID, E.FIRST_NAME, DEPARTMENT_ID,
       D.DEPARTMENT_NAME, L.CITY, J.JOB_TITLE
  FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D
       USING (DEPARTMENT_ID) LEFT JOIN LOCATIONS L
       USING (LOCATION_ID) JOIN JOBS J
       USING (JOB_ID); 
 
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
  FROM EMPLOYEES E FULL OUTER JOIN DEPARTMENTS D
       ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID);
 
 
 
 
 