SELECT '3' + 'X' FROM DUAL;

SELECT EMPLOYEE_ID, HIRE_DATE
  FROM EMPLOYEES WHERE HIRE_DATE > '02/01/01';
  
  
SELECT TO_CHAR(SYSDATE, 'fmDD Month YYYY - Day "hora:" HH24:MI:SS AM') DATA_HORA
FROM DUAL;

SELECT TO_CHAR(12345, 'fmL999G999D00') VALOR FROM DUAL;
SELECT TO_CHAR(0.56, 'fmL999G999G990D00') VALOR FROM DUAL;
SELECT TO_CHAR(123454564, 'fmL999G999G990D00') VALOR FROM DUAL;

SELECT TO_NUMBER('123.454.564,00','990G990G990D90') FROM DUAL;

SELECT TO_DATE('2019 03 14', 'fxYYYY MM DD') FROM DUAL;
--fx só pode se usado com a função TO_DATE

SELECT TO_CHAR(TO_DATE('01/01/1940'), 'DD/MM/YY') FROM DUAL;
SELECT TO_CHAR(TO_DATE('01/01/2040'), 'DD/MM/RR') FROM DUAL;

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY,
       NVL(SALARY * COMMISSION_PCT,0) COMISSÃO,
       NVL2(COMMISSION_PCT,'S','N') RECEBE_COM
  FROM EMPLOYEES;

SELECT FIRST_NAME, LAST_NAME,
       LENGTH(FIRST_NAME) TAM_NOME, LENGTH(LAST_NAME) TAM_SOBRENOME,
       NULLIF(LENGTH(FIRST_NAME), LENGTH(LAST_NAME))
  FROM EMPLOYEES;
  
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY,
       COALESCE(SALARY * COMMISSION_PCT, NULL, NULL, NULL, NULL, NULL, NULL,0) COMISSÃO
  FROM EMPLOYEES;       
  


