-- FEATURES ORACLE 12c+

SELECT EMPLOYEE_ID, FIRST_NAME
  FROM EMPLOYEES
 ORDER BY EMPLOYEE_ID
 FETCH FIRST 5 ROWS ONLY;

SELECT EMPLOYEE_ID, FIRST_NAME
  FROM EMPLOYEES
 ORDER BY EMPLOYEE_ID
 OFFSET 4 ROWS FETCH NEXT 5 ROWS ONLY; 
 
 SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID
   FROM EMPLOYEES
  FETCH FIRST 5 ROWS ONLY;
 
 SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID
   FROM EMPLOYEES
  OFFSET 5 ROWS FETCH NEXT 5 ROWS ONLY;
  
 SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID
   FROM EMPLOYEES
  FETCH FIRST 5 PERCENT ROWS ONLY;
 
 SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID
   FROM EMPLOYEES
  OFFSET 5  ROWS FETCH NEXT 5 PERCENT ROWS ONLY;  
    
 SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID
   FROM EMPLOYEES  
  ORDER BY DEPARTMENT_ID --PRECISA DO ORDER BY
 FETCH FIRST 5 ROWS WITH TIES;
 
 
 UNDEFINE NOVAS_COLUNAS;
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, JOB_ID, &&NOVAS_COLUNAS
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID &ID_DEPT
 ORDER BY &NOVAS_COLUNAS;
 
SELECT FIRST_NAME, LAST_NAME
  FROM EMPLOYEES
 WHERE LAST_NAME LIKE INITCAP('&LETRA%');
 
 
 SELECT SYSDATE FROM DUAL;
 SELECT * FROM DUAL;
 
 
--CARACTER
SELECT UPPER('ka solution unidade morumbi') from dual; 
SELECT INITCAP('ka solution unidade morumbi') from dual; 
SELECT LENGTH('ka solution unidade morumbi') from dual; 
SELECT INSTR('ka solution unidade morumbi', 'um') from dual; 
SELECT CONCAT('KA', CONCAT(' ', 'SOLUTION')) FROM DUAL;
SELECT REPLACE('JACK AND JUE', 'J','BL') FROM DUAL;
SELECT LPAD(LAST_NAME, '30','+') FROM EMPLOYEES;
SELECT RPAD(LAST_NAME, '30','+') FROM EMPLOYEES;
SELECT TRIM('       123        ') AS TESTE FROM DUAL;
SELECT TRIM('A                B') AS TESTE FROM DUAL;
SELECT TRIM(LEADING '*' FROM '***********$***********') FROM DUAL;
SELECT TRIM(TRAILING '*' FROM '***********$***********') FROM DUAL;
SELECT TRIM(BOTH '*' FROM '***********$***********') FROM DUAL;
SELECT SUBSTR('ka solution unidade morumbi',4,8) KA FROM DUAL;
SELECT SUBSTR('ka solution unidade morumbi',-7,2) KA FROM DUAL;
SELECT SUBSTR('ka solution unidade morumbi',4) KA FROM DUAL;
SELECT SUBSTR('ka solution unidade morumbi',-7) KA FROM DUAL;
 
--NUMEROS 
SELECT ROUND(45.962,2) FROM DUAL; 
SELECT ROUND(45.962,1) FROM DUAL; 
SELECT ROUND(45.962,0) FROM DUAL; 
SELECT ROUND(45.962) FROM DUAL; 
SELECT ROUND(45.962,-1) FROM DUAL; 
SELECT ROUND(45.962,-2) FROM DUAL; 


-1 -- 10
-2 -- 100
-3 -- 1000
 
SELECT TRUNC(45.962,2) FROM DUAL; 
SELECT TRUNC(45.962,1) FROM DUAL; 
SELECT TRUNC(45.962,0) FROM DUAL; 
SELECT TRUNC(45.962) FROM DUAL; 
SELECT TRUNC(45.962,-1) FROM DUAL; 
SELECT TRUNC(99.999999,-2) FROM DUAL; 

--DATAS
SELECT SYSDATE, CURRENT_DATE, SESSIONTIMEZONE, CURRENT_TIMESTAMP FROM DUAL;
SELECT MONTHS_BETWEEN('10/08/2018', '04/01/2017') FROM DUAL;
SELECT ADD_MONTHS(SYSDATE, 4) FROM DUAL;
SELECT LAST_DAY('01/02/2019') FROM DUAL;
SELECT ROUND(SYSDATE,'MONTH') FROM DUAL;
SELECT ROUND(SYSDATE,'YEAR') FROM DUAL;
SELECT TRUNC(SYSDATE,'MONTH') FROM DUAL;
SELECT TRUNC(SYSDATE,'YEAR') FROM DUAL;
 
 
 
 
 
 
 
 
 
 
 
 
 