SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;
SELECT FIRST_NAME, SALARY, SALARY + 300 FROM EMPLOYEES;

SELECT FIRST_NAME AS NOME,
       SALARY SALARIO,
       (SALARY + 300) * 1.10 "SALARIO + R$300.00 x 10%"
  FROM EMPLOYEES;
--COMENTÁRIO DE LINHA
/*
  COMENTÁRIO DE BLOCO
*/
SELECT FIRST_NAME, SALARY*12*NVL(COMMISSION_PCT,1) "SAL.ANUAL+COMISSÃO"
  FROM EMPLOYEES;
  
SELECT FIRST_NAME, COMMISSION_PCT FROM EMPLOYEES;
  
SELECT FIRST_NAME || ' - ' || LAST_NAME
  FROM EMPLOYEES;  
  
SELECT FIRST_NAME || ':' ||COMMISSION_PCT FROM EMPLOYEES;  

SELECT FIRST_NAME || q'< é um 'excelente' empregado>' from employees;

SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;

SELECT DISTINCT DEPARTMENT_ID, JOB_ID FROM EMPLOYEES;

DESC EMPLOYEES;
  
  
SELECT FIRST_NAME, JOB_ID, SALARY
  FROM EMPLOYEES
 WHERE FIRST_NAME LIKE '____i%';  
 
SELECT JOB_ID FROM EMPLOYEES
 WHERE JOB_ID LIKE '%#_R%' ESCAPE '#';
 
SELECT FIRST_NAME, JOB_ID, SALARY
  FROM EMPLOYEES
 WHERE FIRST_NAME = 'Steven';  
 
SELECT FIRST_NAME
  FROM EMPLOYEES
 WHERE FIRST_NAME BETWEEN 'A' AND 'E';
 
SELECT FIRST_NAME, LAST_NAME, MANAGER_ID
  FROM EMPLOYEES
 WHERE MANAGER_ID IS NULL;
 
  
  
  
  
  
