SELECT * FROM ORA1.EMPLOYEES;
SELECT * FROM ORA1.DEPARTMENTS;
GRANT SELECT ON ORA1.DEPARTMENTS TO ORA61;

DROP VIEW ORA1EMP;
CREATE VIEW ORA1EMP AS
  SELECT EMPLOYEE_ID, FIRST_NAME, SALARY, JOB_ID
    FROM ORA1.EMPLOYEES;
    
GRANT SELECT ON ORA1EMP TO ORA21;    


    
    
    