SELECT * FROM EMPLOYEES;

SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
  FROM EMPLOYEES;
  
DESCRIBE DEPARTMENTS;
DESC DEPARTMENTS;

SELECT
   DEPARTMENT_NAME,
   DEPARTMENT_ID
FROM
   DEPARTMENTS;
   
SELECT
   EMPLOYEE_ID,
   SALARY,
   SALARY + 2500
FROM
   EMPLOYEES;
  
-- PRIMEIRO * e / DEPOIS + e -
SELECT
   EMPLOYEE_ID,
   SALARY,
   ((SALARY + 200) * 1.2) + 300
FROM
   EMPLOYEES;
