SELECT TRUNC((SYSDATE-HIRE_DATE)/365)
FROM EMPLOYEES ORDER BY 1;

--CASE COM EXPRESSÃO
SELECT EMPLOYEE_ID, LAST_NAME, TRUNC((SYSDATE-HIRE_DATE)/365) QTD_ANOS,
       CASE  TRUNC((SYSDATE-HIRE_DATE)/365)
           WHEN 10 THEN '+5 DIAS'
           WHEN 11 THEN '+6 DIAS'
           WHEN 12 THEN '+7 DIAS'
           WHEN 13 THEN '+8 DIAS'
           ELSE '+10 DIAS'
       END BONUS_DIAS
  FROM EMPLOYEES;
  
--SEARCHED CASE
SELECT EMPLOYEE_ID, LAST_NAME, TRUNC((SYSDATE-HIRE_DATE)/365) QTD_ANOS,
    CASE  
        WHEN TRUNC((SYSDATE-HIRE_DATE)/365) = 10 THEN '+5 DIAS'
        WHEN TRUNC((SYSDATE-HIRE_DATE)/365) = 11 THEN '+6 DIAS'
        WHEN TRUNC((SYSDATE-HIRE_DATE)/365) = 12 THEN '+7 DIAS'
        WHEN TRUNC((SYSDATE-HIRE_DATE)/365) = 13 THEN '+8 DIAS'
        WHEN TRUNC((SYSDATE-HIRE_DATE)/365) >= 14 THEN '+10 DIAS'
        ELSE '+0 DIAS'
    END BONUS_DIAS
  FROM EMPLOYEES; 
  
--DECODE  
SELECT EMPLOYEE_ID, LAST_NAME, TRUNC((SYSDATE-HIRE_DATE)/365) QTD_ANOS,
       DECODE(TRUNC((SYSDATE-HIRE_DATE)/365),
                10, '+5 DIAS',
                11, '+6 DIAS',
                12, '+7 DIAS',
                13, '+8 DIAS',
                    '+10 DIAS') BONUS_DIAS
  FROM EMPLOYEES;
  
SELECT MAX(SALARY) FROM EMPLOYEES;   --24000
SELECT MIN(SALARY) FROM EMPLOYEES;   -- 2500
SELECT AVG(SALARY) FROM EMPLOYEES;   --8775,4 
SELECT COUNT(SALARY) FROM EMPLOYEES; --20 

SELECT COUNT(*) FROM EMPLOYEES;
SELECT COUNT(COMMISSION_PCT) FROM EMPLOYEES;
SELECT AVG(NVL(COMMISSION_PCT,0)) FROM EMPLOYEES;
SELECT COUNT(DISTINCT MANAGER_ID) FROM EMPLOYEES;
SELECT MANAGER_ID FROM EMPLOYEES;

SELECT DEPARTMENT_ID, AVG(SALARY)
  FROM EMPLOYEES
 WHERE HIRE_DATE > TO_DATE('01/01/2004','DD/MM/YYYY')
 GROUP BY DEPARTMENT_ID
 HAVING AVG(SALARY) BETWEEN 4000 AND 15000;

SELECT DEPARTMENT_ID, JOB_ID, AVG(SALARY)
  FROM EMPLOYEES
 WHERE TRUNC((SYSDATE-HIRE_DATE)/365) >= 12
 GROUP BY DEPARTMENT_ID, JOB_ID;
 
 
SELECT E.EMPLOYEE_ID, E.FIRST_NAME,
       E.LAST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
  FROM EMPLOYEES E JOIN DEPARTMENTS D
       ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
          AND E.MANAGER_ID = D.MANAGER_ID;
       
SELECT E.EMPLOYEE_ID, E.FIRST_NAME,
       E.LAST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME,
       J.JOB_ID, J.JOB_TITLE
  FROM EMPLOYEES E JOIN DEPARTMENTS D
       ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
       JOIN JOBS J
       ON (E.JOB_ID = J.JOB_ID);

--TODOS OS EMPREGADOS
SELECT E.EMPLOYEE_ID, E.FIRST_NAME,
       E.LAST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
  FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D
       ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID);

--TODOS OS DEPARTAMENTOS
SELECT E.EMPLOYEE_ID, E.FIRST_NAME,
       E.LAST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
  FROM EMPLOYEES E RIGHT JOIN DEPARTMENTS D
       ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID);

--TODOS OS DEPARTAMENTOS E TODOS EMPREGADOS
SELECT E.EMPLOYEE_ID, E.FIRST_NAME,
       E.LAST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
  FROM EMPLOYEES E FULL JOIN DEPARTMENTS D
       ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID);

SELECT E.EMPLOYEE_ID, E.FIRST_NAME,
       E.LAST_NAME, DEPARTMENT_ID, D.DEPARTMENT_NAME
  FROM EMPLOYEES E NATURAL JOIN DEPARTMENTS D;

SELECT E.EMPLOYEE_ID, E.FIRST_NAME,
       E.LAST_NAME, DEPARTMENT_ID, D.DEPARTMENT_NAME
  FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D
       USING (DEPARTMENT_ID, MANAGER_ID);
       
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.MANAGER_ID,
       G.FIRST_NAME
  FROM EMPLOYEES E JOIN EMPLOYEES G
       ON E.MANAGER_ID = G.EMPLOYEE_ID;
       
SELECT EMPLOYEE_ID, DEPARTMENT_NAME
  FROM EMPLOYEES CROSS JOIN DEPARTMENTS
 WHERE DEPARTMENT_NAME = 'Marketing';
 
SELECT * FROM JOB_GRADES; 

SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.SALARY,
       J.GRADE_LEVEL, J.LOWEST_SAL, J.HIGHEST_SAL
  FROM EMPLOYEES E JOIN JOB_GRADES J
       ON (E.SALARY BETWEEN J.LOWEST_SAL AND J.HIGHEST_SAL);

