SELECT DEPARTMENT_ID, DEPARTMENT_NAME, CITY,
       COUNTRY_NAME, REGION_NAME, EMPLOYEE_ID,
       FIRST_NAME, JOB_TITLE, SALARY
  FROM DEPARTMENTS DEP JOIN LOCATIONS LOC USING(LOCATION_ID)
       JOIN COUNTRIES CTR USING(COUNTRY_ID)
       JOIN REGIONS REG USING(REGION_ID)
       RIGHT JOIN EMPLOYEES EMP USING(DEPARTMENT_ID)
       JOIN JOBS JOB USING(JOB_ID);
       
SELECT DISTINCT E.EMPLOYEE_ID, E.FIRST_NAME, E.DEPARTMENT_ID
  FROM EMPLOYEES E JOIN EMPLOYEES M
       ON (E.EMPLOYEE_ID = M.MANAGER_ID);
       
SELECT DEPARTMENT_ID, EMPLOYEE_ID, FIRST_NAME, SALARY
  FROM EMPLOYEES
 WHERE (DEPARTMENT_ID, SALARY) IN
                   (SELECT DEPARTMENT_ID, MIN(SALARY)
                      FROM EMPLOYEES
                     GROUP BY DEPARTMENT_ID);
                     
SELECT EMPLOYEE_ID, FIRST_NAME, SALARY
  FROM EMPLOYEES
 WHERE SALARY != ALL (2500, 8600 ,9000, 12000 , NULL);

UNDEFINE ID_EMPLOYEE; 
SELECT EMPLOYEE_ID, JOB_ID, FIRST_NAME, SALARY
  FROM EMPLOYEES /* 107 - DIANA - IT_PROG - 4200 */
 WHERE JOB_ID = (SELECT JOB_ID
                   FROM EMPLOYEES
                  WHERE EMPLOYEE_ID = '&&ID_EMPLOYEE')
   AND SALARY > (SELECT SALARY
                   FROM EMPLOYEES
                  WHERE EMPLOYEE_ID = '&ID_EMPLOYEE');
                  



SELECT EMPLOYEE_ID, FIRST_NAME
  FROM EMPLOYEES
 WHERE MANAGER_ID = (SELECT EMPLOYEE_ID
                       FROM EMPLOYEES
                      WHERE UPPER(LAST_NAME)
                        = UPPER('&SOBRENOME'));
                        
SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME, EMP.LAST_NAME,
       EMP.DEPARTMENT_ID, EMP.SALARY
  FROM EMPLOYEES EMP
  JOIN (SELECT DEPARTMENT_ID, AVG(SALARY) MED_SALARY
          FROM EMPLOYEES
         GROUP BY DEPARTMENT_ID) MED
    ON EMP.DEPARTMENT_ID = MED.DEPARTMENT_ID
   AND EMP.SALARY > MED.MED_SALARY;
                  
                  
SELECT JOB_ID FROM EMPLOYEES
UNION ALL
SELECT JOB_ID FROM JOB_HISTORY;

SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES
INTERSECT
SELECT EMPLOYEE_ID, JOB_ID
FROM JOB_HISTORY;

SELECT EMPLOYEE_ID, JOB_ID
FROM EMPLOYEES
MINUS
SELECT EMPLOYEE_ID, JOB_ID
FROM JOB_HISTORY;        

SELECT DEPARTMENT_ID, DEPARTMENT_NAME
  FROM EMPLOYEES JOIN DEPARTMENTS USING (DEPARTMENT_ID)
  WHERE SALARY > 8000
MINUS
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
  FROM DEPARTMENTS JOIN LOCATIONS USING (LOCATION_ID)
WHERE CITY = 'Toronto';
        
SELECT EMPLOYEE_ID
  FROM EMPLOYEES
MINUS
SELECT EMPLOYEE_ID
  FROM JOB_HISTORY;
  
DESC DEPARTMENTS;  

SELECT EMPLOYEE_ID "ID",
       FIRST_NAME "NOME",
       SALARY "SALARIO",
       MANAGER_ID "GERENTE"
  FROM EMPLOYEES
UNION
SELECT DEPARTMENT_ID,
       DEPARTMENT_NAME,
       0,
       MANAGER_ID
  FROM DEPARTMENTS;
  
SELECT EMPLOYEE_ID, FIRST_NAME,
       DEPARTMENT_ID, SALARY, 'DEPT. 10,20 ou 90'
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID IN (10,20,90)
UNION  
SELECT EMPLOYEE_ID, FIRST_NAME,
       DEPARTMENT_ID, SALARY, 'SOBRENOME COMEÇA COM "A"'
  FROM EMPLOYEES
 WHERE LAST_NAME LIKE 'A%';
 
 SELECT DEPARTMENT_ID
   FROM DEPARTMENTS
 MINUS
 SELECT DEPARTMENT_ID
   FROM EMPLOYEES
  WHERE JOB_ID = 'SA_REP';
  
  
SELECT EMPLOYEE_ID, FIRST_NAME
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = 80
INTERSECT 
SELECT EMPLOYEE_ID, FIRST_NAME
  FROM EMPLOYEES
 WHERE JOB_ID = 'SA_REP';

  
  
  
  



  
 

       
       
       
       
       
       
       
       