 CREATE TABLE CURSO (
     COD_CURSO  NUMBER(10) CONSTRAINT PK_CURSO PRIMARY KEY,
     NOM_CURSO  VARCHAR2(30 CHAR) NOT NULL,
     DAT_INICIO DATE,
     DAT_FIM    DATE,
     CONSTRAINT CK_DATA CHECK(DAT_FIM > DAT_INICIO));

 CREATE TABLE ALUNO (
     COD_ALUNO      NUMBER(10) CONSTRAINT PK_ALUNO PRIMARY KEY,
     NUM_MATRICULA  VARCHAR2(10 CHAR) NOT NULL,
     NOM_ALUNO      VARCHAR2(50 CHAR) NOT NULL,
     DAT_MATRICULA  DATE DEFAULT SYSDATE,
     NOM_CIDADE     VARCHAR2(40 CHAR) DEFAULT 'SÃO PAULO',
     NUM_IDADE      NUMBER(3)
       CONSTRAINT CK_MAIOR CHECK(NUM_IDADE >= 18),
     DES_EMAIL      VARCHAR2(255) CONSTRAINT UK_EMAIL UNIQUE,
     COD_CURSO NUMBER(10)
       CONSTRAINT FK_CURSO REFERENCES CURSO(COD_CURSO),
     CONSTRAINT CK_EMAIL_MIN
       CHECK(LOWER(DES_EMAIL) = DES_EMAIL)  
         /* ON DELETE CASCADE*/ );
   --NO NIVEL DA TABELA:
   /*COD_CURSO NUMBER(10),
       CONSTRAINT FK_CURSO FOREIGN KEY (COD_CURSO)
       REFERENCES CURSO(COD_CURSO)ON DELETE CASCADE); */
       
       
       
INSERT INTO CURSO VALUES
  (95000, 'SQL I e II',
   TO_DATE('26/01/2018','DD/MM/YYYY'),
   TO_DATE('05/03/2018','DD/MM/YYYY'));
COMMIT;
       
INSERT INTO CURSO VALUES
  (95001, 'PL/SQL',
   TO_DATE('07/03/2018','DD/MM/YYYY'),
   TO_DATE('04/04/2018','DD/MM/YYYY'));
COMMIT;
       
INSERT INTO ALUNO (COD_ALUNO, NUM_MATRICULA, NOM_ALUNO,
                   NUM_IDADE, DES_EMAIL, COD_CURSO)
           VALUES (1, 'MA00523','VICTOR BRUM SILVA',
                   25, 'victor@gmail.com', 95000);
COMMIT;

SELECT * FROM ALUNO;
       
INSERT INTO ALUNO (COD_ALUNO, NUM_MATRICULA, NOM_ALUNO,
                   NUM_IDADE, DES_EMAIL, COD_CURSO)
           VALUES (2, 'MA00524','DAYSE CLAUDIA SANTOS',
                   18, 'dayse@gmail.com', 95001);
COMMIT;

SELECT * FROM ALUNO;
       
DELETE CURSO WHERE COD_CURSO = 95001;

TRUNCATE TABLE CURSO;

CREATE TABLE EMP2(ID, NOME, SAL) AS
  SELECT EMPLOYEE_ID, FIRST_NAME,
         SALARY * 1.2
    FROM EMPLOYEES;

SELECT * FROM EMP2;


ALTER TABLE ALUNO ADD
   (NOM_UNIDADE VARCHAR2(20 CHAR) DEFAULT 'MORUMBI');

SELECT * FROM ALUNO;

ALTER TABLE ALUNO MODIFY
   (NOM_UNIDADE VARCHAR2(40 CHAR));

DESC ALUNO;

ALTER TABLE ALUNO
   SET UNUSED (NOM_UNIDADE);
DESC ALUNO;   
ALTER TABLE ALUNO
   DROP UNUSED COLUMNS;
   

SELECT * FROM DICTIONARY
 WHERE TABLE_NAME
    IN ('USER_TABLES','ALL_TABLES','DBA_TABLES');
    
SELECT * FROM USER_TABLES;    
SELECT * FROM ALL_TABLES;
SELECT * FROM DBA_TABLES;    


SELECT * FROM DICT WHERE TABLE_NAME LIKE 'USER_%';
SELECT * FROM USER_CONSTRAINTS
 WHERE TABLE_NAME = 'ALUNO';
 
SELECT OWNER,
       TABLE_NAME,
       COLUMN_NAME,
       DATA_TYPE,
       CHAR_LENGTH,
       CHAR_USED
       FROM ALL_TAB_COLUMNS
 WHERE TABLE_NAME = 'ALUNO'; 
 
 SELECT 'TRUNKATE TABLE ' || TABLE_NAME || ';'
   FROM USER_TABLES;
   
COMMENT ON TABLE ALUNO
  IS 'ALUNOS DOS CURSOS DA KA MORUMBI/CENTRO';
  
COMMENT ON COLUMN ALUNO.NUM_IDADE
  IS 'IDADE DOS ALUNOS. SÓ PODE SER > QUE 18';
  
SELECT * FROM USER_TAB_COMMENTS
 WHERE TABLE_NAME = 'ALUNO';
 
SELECT * FROM USER_COL_COMMENTS
 WHERE TABLE_NAME = 'ALUNO';
   






       
       
       
       
       
       
       
       
         