SELECT LOWER('Curso Fundamentos SQL') FROM DUAL;
SELECT LOWER(FIRST_NAME) FROM EMPLOYEES;
SELECT UPPER(FIRST_NAME) FROM EMPLOYEES;
SELECT INSTR('HelloWorldW','WWW') FROM DUAL;
SELECT LPAD(FIRST_NAME,12,'*') FROM EMPLOYEES;
SELECT RPAD(UPPER(FIRST_NAME),12,'*-') FROM EMPLOYEES;
SELECT ROUND(10/3,4) FROM DUAL;
SELECT ROUND(64.100, -2) FROM DUAL;
SELECT TRUNC(49, -1) FROM DUAL;
SELECT CEIL(2.01) FROM DUAL;
SELECT FLOOR(2.9999) FROM DUAL;
SELECT TRUNC(2.9999) FROM DUAL;

10    -1
100   -2
1000  -3
10000 -4

DD/MM/YYYY
DD/MM/RR

SELECT SYSDATE+7 FROM DUAL;
SELECT CURRENT_TIMESTAMP FROM DUAL;
SELECT NEXT_DAY(SYSDATE, 'SEXTA') FROM DUAL;
SELECT NEXT_DAY(SYSDATE, 1) FROM DUAL;
/*
1 - DOMINGO
7 - SÁBADO
*/
SELECT EMPLOYEE_ID, FIRST_NAME,
       HIRE_DATE, ADD_MONTHS(HIRE_DATE,3)
  FROM EMPLOYEES
 WHERE DEPARTMENT_ID = 60;


SELECT ROUND(SYSDATE+15, 'MONTH') FROM DUAL;
SELECT ROUND(ADD_MONTHS(SYSDATE,6), 'YEAR') FROM DUAL;
SELECT TRUNC(SYSDATE, 'MONTH') FROM DUAL;
SELECT TRUNC(SYSDATE, 'YEAR') FROM DUAL;
/*
1 - MONTAR UMA QUERY QUE MOSTRE O EMPLOYEE_ID,
FIRST_NAME, LAST_NAME E SALARY DOS FUNCIONARIOS
CUJO FIRST_NAME CONCATENADO COM O LAST_NAME TENHA MAIS
DE 6 LETRAS
*/

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
  FROM EMPLOYEES
 WHERE LENGTH(CONCAT(FIRST_NAME,LAST_NAME)) > 6;
 
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
  FROM EMPLOYEES
 WHERE LENGTH(FIRST_NAME||LAST_NAME) > 6;
/* 
2 - MONTAR UMA QUERY QUE MOSTRE O EMPLOYEE_ID, 
O DEPARTMENT_ID E AS 3 PRIMEIRAS LETRAS DO FIRST_NAME
DO EMPREGADO. COMPLETAR AS LETRAS COM # ATÉ QUE FIQUE
COM 10 CARACTERES (MOSTRAR O RESULTADO EM LETRAS
MAIÚSCULAS)
*/

SELECT EMPLOYEE_ID, DEPARTMENT_ID,
       RPAD(SUBSTR(UPPER(FIRST_NAME), 1, 3),10,'#')
  FROM EMPLOYEES;       

/*
3 - DATA DO EXAME MÉDICO. TODO EMPREGADO DEVE FAZER 
EXAME NA PRIMEIRA SEGUNDA-FEIRA SEIS MESES APOS A
DATA DE CONTRATAÇÃO (HIRE_DATE). MOSTRAR O EMPLOYEE_ID,
FIRST_NAME, HIRE_DATE E DATA_EXAME DE TODOS EMPREGADOS.
*/

SELECT EMPLOYEE_ID, FIRST_NAME, HIRE_DATE,
       NEXT_DAY(ADD_MONTHS(HIRE_DATE,6),2)
  FROM EMPLOYEES;
  
  
  --CAPITULO 5
  
SELECT TO_NUMBER('3') + TO_NUMBER('3') FROM DUAL;
SELECT 'DOIS' + 'DOIS' FROM DUAL;

SELECT FIRST_NAME, HIRE_DATE
  FROM EMPLOYEES
 WHERE HIRE_DATE LIKE '%03';
 
SELECT FIRST_NAME, SALARY
  FROM EMPLOYEES
 WHERE SALARY > TO_NUMBER('8000');
 
SELECT TO_CHAR(SYSDATE,'DD MONTH YYYY - DAY HH24:MI:SS') FROM DUAL;

SELECT TO_CHAR(SYSDATE,'DD/MON/YYYY - DAY') FROM DUAL;
SELECT FIRST_NAME, TO_CHAR(HIRE_DATE,'DD MONTH YYYY fm- DAY HH24:MI:SS')
  FROM EMPLOYEES;
SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS AM') FROM DUAL; 
SELECT TO_CHAR(SYSDATE, 'DD "de" MONTH') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'ddspth') FROM DUAL;
  
  
SELECT EMPLOYEE_ID, FIRST_NAME,
       TO_CHAR(SALARY, 'fmL999G999D00')
  FROM EMPLOYEES;
  
SELECT FIRST_NAME,
       TO_CHAR(SALARY, 'fmL999G999D00') SALARIO,
       TO_CHAR(HIRE_DATE, 'DD/MM/YYYY - DY') CONTRATADO
  FROM EMPLOYEES
 WHERE HIRE_DATE > TO_DATE('20030701','YYYYMMDD');
  
SELECT TO_NUMBER('R$24.800,00','L999G999D00') FROM DUAL;  

SELECT EMPLOYEE_ID, SALARY,
       SALARY + SALARY * NVL(COMMISSION_PCT,0) "SAL+COM",
       NVL2(COMMISSION_PCT,'RECEBE COM.','NÃO RECEBE') "COMISSÃO?"
  FROM EMPLOYEES;       
  
SELECT EMPLOYEE_ID, SALARY,
       SALARY + SALARY * COALESCE(COMMISSION_PCT,0) "SAL+COM",
       NVL2(COMMISSION_PCT,'RECEBE COM.','NÃO RECEBE') "COMISSÃO?"
  FROM EMPLOYEES;       
  
  
       
       
       
       
       
       
       
       
       
       
       

