--SELECT * FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG';
DECLARE
  V_ALTERADO NUMBER;
BEGIN
   UPDATE EMPLOYEES
      SET SALARY = SALARY * 1.10
    WHERE JOB_ID = 'IT_PROG';
    
    V_ALTERADO := SQL%ROWCOUNT;
    DBMS_OUTPUT.PUT_LINE('EMPREGADOS ALTERADOS: '||V_ALTERADO);
END;