DECLARE
   V_JOB_ID EMPLOYEES.JOB_ID%TYPE := 'IT_PROG';
   V_DEPARTMENT_ID EMPLOYEES.EMPLOYEE_ID%TYPE := 50;
   E_DEPT_INCORRETO EXCEPTION;
BEGIN
   IF (V_JOB_ID = 'IT_PROG' AND V_DEPARTMENT_ID != 60) THEN
      RAISE E_DEPT_INCORRETO;
   END IF;
   
   INSERT INTO EMPLOYEES(EMPLOYEE_ID, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID, DEPARTMENT_ID)
        VALUES (1000, 'RIBEIRO', 'RIGOR',SYSDATE, V_JOB_ID, V_DEPARTMENT_ID);
        
   EXCEPTION
      WHEN E_DEPT_INCORRETO THEN
         DBMS_OUTPUT.PUT_LINE('TODO IT_PROG DEVE TRABALHAR NO DEPT. 60.');
END;
/
SELECT * FROM EMPLOYEES WHERE EMPLOYEE_ID = 1000;