CREATE OR REPLACE PACKAGE PKG_LOG IS
   TYPE T_LOG IS TABLE OF SISLOG%ROWTYPE;
   V_LOG T_LOG;
   
   PROCEDURE LOAD_LOG(P_LOG OUT NOCOPY T_LOG);
END PKG_LOG;
/
CREATE OR REPLACE PACKAGE BODY PKG_LOG IS
   PROCEDURE LOAD_LOG(P_LOG OUT NOCOPY T_LOG) IS
      CURSOR C_LOG IS SELECT * FROM SISLOG;
   BEGIN
      OPEN C_LOG;
      FETCH C_LOG BULK COLLECT INTO P_LOG;
      CLOSE C_LOG;
   END LOAD_LOG;
END PKG_LOG;
/








