SET SERVEROUTPUT ON
DECLARE
   V_BASIC_PERCENT NUMBER := 45;
   V_SALARY EMPLOYEES.SALARY%TYPE;
   V_FNAME EMPLOYEES.FIRST_NAME%TYPE;
   V_DESCONTO NUMBER(10,2);
BEGIN
   SELECT FIRST_NAME, SALARY INTO V_FNAME, V_SALARY
     FROM EMPLOYEES WHERE EMPLOYEE_ID = 103;
   V_DESCONTO := V_SALARY * (V_BASIC_PERCENT/100);
   DBMS_OUTPUT.PUT_LINE('OLÁ '||V_FNAME||', SEU DESCONTO SERÁ DE '
      ||TO_CHAR(V_DESCONTO, 'fmL999G999D00'));
END;