SET SERVEROUTPUT ON
DECLARE
   V_VALOR_INICIAL NUMBER := 2500;
   V_VALOR_PRETENDIDO NUMBER := 12000;
   V_MESES NUMBER := 0;
BEGIN
   LOOP
      V_MESES := V_MESES + 1;
      V_VALOR_INICIAL := V_VALOR_INICIAL * 1.10;
      EXIT WHEN V_VALOR_INICIAL >= V_VALOR_PRETENDIDO;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('QTD. MESES: '|| V_MESES);
    DBMS_OUTPUT.PUT_LINE('VALOR FINAL: '||TO_CHAR(V_VALOR_INICIAL, 'fmL999G990D00'));
END;
/