DECLARE
   V_SALARY EMPLOYEES.SALARY%TYPE;
BEGIN
   SELECT MAX(SALARY) INTO V_SALARY
     FROM EMPLOYEES;
   DBMS_OUTPUT.PUT_LINE('MAIOR SALÁRIO: '||TO_CHAR(V_SALARY,'fmL999G990D00'));     
END;