DECLARE 
   V_COUNTRIES COUNTRIES%ROWTYPE;
   V_COUNTRY_ID V_COUNTRIES.COUNTRY_ID%TYPE := 'CA';
BEGIN
   SELECT * INTO V_COUNTRIES
     FROM COUNTRIES
    WHERE COUNTRY_ID = V_COUNTRY_ID;
    
   DBMS_OUTPUT.PUT_LINE('ID: ' || V_COUNTRIES.COUNTRY_ID);
   DBMS_OUTPUT.PUT_LINE('NOME: ' || V_COUNTRIES.COUNTRY_NAME);
   DBMS_OUTPUT.PUT_LINE('REGIÃO: ' || V_COUNTRIES.REGION_ID);
   
END;
/  