DECLARE
   E_VIOLACAO_PK EXCEPTION;
   PRAGMA EXCEPTION_INIT(E_VIOLACAO_PK, -00001);
   E_VALOR_NULO EXCEPTION;
   PRAGMA EXCEPTION_INIT(E_VALOR_NULO, -01400);
BEGIN
   --INSERT INTO DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME)
   --       VALUES (10, 'TESTE');
   INSERT INTO DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME)
          VALUES (10, NULL);
          
   EXCEPTION
      WHEN E_VIOLACAO_PK THEN
         DBMS_OUTPUT.PUT_LINE('VIOLAÇÃO DA CHAVE PRIMÁRIA: '||SQLERRM);
         DBMS_OUTPUT.PUT_LINE('CODIGO DO ERRO: '||SQLCODE);
      WHEN E_VALOR_NULO THEN
         DBMS_OUTPUT.PUT_LINE('VALOR NULO PARA COLUNA: '||SQLERRM);
END;
/