SET VERIFY OFF
DECLARE
   CURSOR C_EMPS(V_SAL NUMBER, V_DEPT NUMBER) IS 
          SELECT EMPLOYEE_ID, DEPARTMENT_ID, SALARY
            FROM EMPLOYEES
           WHERE SALARY > V_SAL
             AND DEPARTMENT_ID = V_DEPT;
   V_EMP_REC C_EMPS%ROWTYPE;             
BEGIN
   OPEN C_EMPS(&VALOR_SALARIO, &NUM_DEPARTAMENTO);
   LOOP
      FETCH C_EMPS INTO V_EMP_REC;
      EXIT WHEN C_EMPS%NOTFOUND;
       DBMS_OUTPUT.PUT_LINE('EMP.ID: '||V_EMP_REC.EMPLOYEE_ID);
       DBMS_OUTPUT.PUT_LINE('DPT.ID: '||V_EMP_REC.DEPARTMENT_ID);
       DBMS_OUTPUT.PUT_LINE('SALARY: '||TO_CHAR(V_EMP_REC.SALARY,'fmL999G990D00'));
       DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------');
   END LOOP;
   CLOSE C_EMPS;
END;