ALTER SESSION SET PLSQL_WARNINGS='ENABLE:ALL';

CREATE OR REPLACE PROCEDURE SP_ATUALIZA_NOTAS
IS
   TYPE T_CODIGO IS TABLE OF NOTAS.CD_ALUNO%TYPE;
   V_CODIGOS T_CODIGO;
BEGIN
   UPDATE NOTAS SET NN_NOTA4 = NN_NOTA4 + 1
    WHERE NN_NOTA4 < 9
    RETURNING CD_ALUNO BULK COLLECT INTO V_CODIGOS;
    
    FOR I IN V_CODIGOS.FIRST..V_CODIGOS.LAST LOOP
       DBMS_OUTPUT.PUT_LINE('ALUNO AFETADO: '||V_CODIGOS(I));
    END LOOP;       
END;   
/