DECLARE
   V_SALARY EMPLOYEES.SALARY%TYPE;
BEGIN
   SELECT SALARY INTO V_SALARY
     FROM EMPLOYEES
    WHERE DEPARTMENT_ID = 30;

   EXCEPTION
      WHEN TOO_MANY_ROWS THEN
         DBMS_OUTPUT.PUT_LINE('MUITAS LINHAS RETORNADAS, REFINE A BUSCA');
      WHEN OTHERS THEN
         DBMS_OUTPUT.PUT_LINE('OCORREU ALGO INESPERADO. LIGUE PARA O SUPORTE!');
END;