--TRUNCATE TABLE MESSAGES;
--CREATE TABLE MESSAGES (RESULTS VARCHAR2(80 CHAR));
BEGIN
   FOR I IN 1..10 LOOP
      IF I NOT IN (6,8) THEN
         INSERT INTO MESSAGES VALUES (I);
      END IF;         
   END LOOP;
END;
/
BEGIN
   FOR I IN 1..10 LOOP
      CONTINUE WHEN I IN (6,8);
      INSERT INTO MESSAGES VALUES (I);
   END LOOP;
END;
/
SELECT * FROM MESSAGES;
