DECLARE 
   V_COUNTRIES COUNTRIES%ROWTYPE;
   V_COUNTRY_ID V_COUNTRIES.COUNTRY_ID%TYPE := 'CA';
BEGIN
   SELECT * INTO V_COUNTRIES
     FROM COUNTRIES
    WHERE COUNTRY_ID = V_COUNTRY_ID;
    
   DBMS_OUTPUT.PUT_LINE('ID: ' || V_COUNTRIES.COUNTRY_ID);
   DBMS_OUTPUT.PUT_LINE('NOME: ' || V_COUNTRIES.COUNTRY_NAME);
   DBMS_OUTPUT.PUT_LINE('REGIÃO: ' || V_COUNTRIES.REGION_ID);
   
END;
/  

SELECT * FROM COUNTRIES;

DECLARE
   V_ID EMPLOYEES.DEPARTMENT_ID%TYPE := 50;
   TYPE T_DEPT IS RECORD (
       DEPT_ID EMPLOYEES.DEPARTMENT_ID%TYPE,
       EMPS NUMBER(10),
       SOMA_SAL NUMBER(10,2),
       MEDIA_SAL NUMBER(10,2));
   V_DEPT T_DEPT;
BEGIN
    SELECT DEPARTMENT_ID, COUNT(*), SUM(SALARY), AVG(SALARY) INTO V_DEPT
      FROM EMPLOYEES WHERE DEPARTMENT_ID = 50
     GROUP BY DEPARTMENT_ID;
   
    DBMS_OUTPUT.PUT_LINE('ID: ' || V_DEPT.DEPT_ID);
    DBMS_OUTPUT.PUT_LINE('SOMA DOS SALÁRIOS: ' || TO_CHAR(V_DEPT.SOMA_SAL, 'fmL999G990D00'));
    DBMS_OUTPUT.PUT_LINE('MÉDIA SALARIAL: ' || TO_CHAR(V_DEPT.MEDIA_SAL, 'fmL999G990D00'));

END;

/