DECLARE 
   V_COUNTRIES COUNTRIES%ROWTYPE;
   V_COUNTRY_ID V_COUNTRIES.COUNTRY_ID%TYPE := 'CA';
BEGIN
   SELECT * INTO V_COUNTRIES
     FROM COUNTRIES
    WHERE COUNTRY_ID = V_COUNTRY_ID;
    
   V_COUNTRIES.COUNTRY_NAME := UPPER(V_COUNTRIES.COUNTRY_NAME); 
   V_COUNTRIES.REGION_ID := 1;
   
   UPDATE COUNTRIES SET ROW = V_COUNTRIES
    WHERE COUNTRY_ID = V_COUNTRY_ID;  
    
   DBMS_OUTPUT.PUT_LINE('ID: ' || V_COUNTRIES.COUNTRY_ID);
   DBMS_OUTPUT.PUT_LINE('NOME: ' || V_COUNTRIES.COUNTRY_NAME);
   DBMS_OUTPUT.PUT_LINE('REGIÃO: ' || V_COUNTRIES.REGION_ID);
END;
/  
SELECT * FROM COUNTRIES WHERE COUNTRY_ID = 'CA';