SET SERVEROUTPUT ON;
DECLARE
   V_HOJE DATE := SYSDATE;
   V_AMANHA V_HOJE%TYPE := V_HOJE + 1;
BEGIN
   DBMS_OUTPUT.PUT_LINE('HOJE É: ' || TO_CHAR(V_HOJE, 'fmDD "de" Month, YYYY'));
   DBMS_OUTPUT.PUT_LINE('AMANHÃ SERÁ: ' || V_AMANHA);
END;