DECLARE
   V_FEEDBACK VARCHAR2(100);
BEGIN
   V_FEEDBACK := 'INSERINDO O CURSO JAVA BÁSICO!';
   SP_INSERE_CURSO(P_NM_CURSO => 'JAVA BÁSICO', P_FEEDBACK => V_FEEDBACK);
   DBMS_OUTPUT.PUT_LINE(V_FEEDBACK);
END;
/