--DESC EMPLOYEES;
--SELECT * FROM EMPLOYEES;
DECLARE
   C_ID CONSTANT NUMBER := 104;
   V_NOME EMPLOYEES.FIRST_NAME%TYPE; --VARCHAR2(20);
   V_ADMISSAO EMPLOYEES.HIRE_DATE%TYPE;
BEGIN
   SELECT UPPER(FIRST_NAME), HIRE_DATE INTO V_NOME, V_ADMISSAO
     FROM EMPLOYEES
    WHERE EMPLOYEE_ID = C_ID;
    DBMS_OUTPUT.PUT_LINE('CODIGO: '||C_ID);
    DBMS_OUTPUT.PUT_LINE('FUNCIONÁRIO: '||UPPER(V_NOME));
    DBMS_OUTPUT.PUT_LINE('CODIGO DT.ADMISSÃO: '||V_ADMISSAO);
END;
/