--VARCHAR - APELIDO
--VARCHAR2(30 BYTE) -> 30 BYTES

DECLARE
   V_MEUNOME VARCHAR2(30 CHAR);
BEGIN
   --BLOCO EXECUTÁVEL
   V_MEUNOME := 'IGOR RIBEIRO';
   DBMS_OUTPUT.PUT_LINE('MEU NOME É: ' || V_MEUNOME || '!');
END;