EXEC SP_INSERE_CURSO('PROGRAMAÇÃO PL/SQL II');
/
SELECT * FROM CURSO;
/
ALTER TABLE CURSO ADD (
   DT_INICIO DATE,
   DT_FIM DATE);
/
EXEC SP_INSERE_CURSO(P_DT_INICIO => SYSDATE, P_NM_CURSO => 'SAP', P_DT_FIM => SYSDATE + 5);
/
DESC SP_INSERE_CURSO;
/
EXEC SP_INSERE_CURSO(P_NM_CURSO => 'SQL AVANÇADO', P_DT_FIM => TO_DATE('30/12/2018'));
/
SELECT * FROM CURSO;
/


