CREATE SEQUENCE SQ_CD_NOTA START WITH 1 INCREMENT BY 1;

CREATE TABLE NOTAS (
   CD_NOTA NUMBER(10) PRIMARY KEY,
   CD_ALUNO NUMBER(10) REFERENCES ALUNO(CD_ALUNO),
   NN_NOTA1 NUMBER(10,2) NOT NULL,
   NN_NOTA2 NUMBER(10,2) NOT NULL,
   NN_NOTA3 NUMBER(10,2) NOT NULL,
   NN_NOTA4 NUMBER(10,2) NOT NULL,
   NN_MEDIA NUMBER(10,2) DEFAULT 0 NOT NULL);