CREATE SEQUENCE SQ_CD_ALUNO START WITH 1 INCREMENT BY 1;

CREATE TABLE ALUNO  (
   CD_ALUNO       NUMBER(10) PRIMARY KEY,
   NM_MATRICULA   VARCHAR2(8 CHAR) NOT NULL,
   NM_NOME        VARCHAR2(50 CHAR) NOT NULL,
   DS_EMAIL       VARCHAR2(255));