CREATE SEQUENCE SQ_CD_SISLOG START WITH 1 INCREMENT BY 1;

CREATE TABLE SISLOG (
   CD_SISLOG NUMBER(10) PRIMARY KEY,
   NM_USUARIO VARCHAR2(40 CHAR) NOT NULL,
   NM_HOST VARCHAR2(40 CHAR) NOT NULL,
   DS_DATA_HORA VARCHAR2(20 CHAR) NOT NULL,
   DS_OPERACAO VARCHAR2(4000 CHAR) NOT NULL);
   
DESC SISLOG;   