SET SERVEROUTPUT ON
BEGIN
   PKG_LOG.LOAD_LOG(PKG_LOG.V_LOG);
   FOR I IN PKG_LOG.V_LOG.FIRST..PKG_LOG.V_LOG.LAST LOOP
      DBMS_OUTPUT.PUT_LINE(PKG_LOG.V_LOG(I).DS_OPERACAO);
   END LOOP;
END;
/
--SELECT * FROM SISLOG;