ALTER TRIGGER TR_AUDITORIA DISABLE;
/
CREATE OR REPLACE TRIGGER TR_LOGON AFTER LOGON ON DATABASE
BEGIN
   SP_GRAVA_LOG('LOGOU NO BANCO DE DADOS');
END;
/
ALTER TRIGGER TR_AUDITORIA ENABLE;
/
SELECT * FROM SISLOG ORDER BY 1;
