SET SERVEROUTPUT ON
BEGIN
   PKG_TREINAMENTO.SP_INSERE_ALUNO('TESTE','teste@teste.com.br');
   DBMS_OUTPUT.PUT_LINE(PKG_TREINAMENTO.V_SUCESSO);
END;   
/
UPDATE ALUNO SET NM_NOME = 'TESTE' WHERE CD_ALUNO = 1;
DELETE ALUNO WHERE CD_ALUNO = 1;


SELECT * FROM ALUNO;
SELECT * FROM SISLOG;
SELECT SQ_CD_SISLOG.CURRVAL FROM DUAL;
