BEGIN PKG_TREINAMENTO.SP_INSERE_ALUNO('MANOEL FRANÇA','mfranca@gmail.com'); END;
/
BEGIN PKG_TREINAMENTO.SP_INSERE_NOTAS(SQ_CD_ALUNO.CURRVAL, 7.50, 7.00, 8.00, 8.00); END;
/
BEGIN  DBMS_OUTPUT.PUT_LINE(PKG_TREINAMENTO.V_SUCESSO); END;   
/
SELECT * FROM ALUNO NATURAL JOIN NOTAS ORDER BY 1;
/
BEGIN
   PKG_TREINAMENTO.SP_INSERE_ALUNO('RODRIGO MAGALHÃES','rodrigom@gmail.com');
   PKG_TREINAMENTO.SP_INSERE_NOTAS(SQ_CD_ALUNO.CURRVAL, 7, 7, 9, 9);
   DBMS_OUTPUT.PUT_LINE(PKG_TREINAMENTO.V_SUCESSO);
END;  
/
BEGIN
   PKG_TREINAMENTO.SP_INSERE_NOTAS(3, 7.0, 7.5, 8.0, 7.5);
END;
/

