1) MOSTRE OS TODOS OS FUNCIONARIO (EMPLOYEE_ID E FIRST_NAME)
QUE TRABALHAM NO DEPARTAMENTO 80 OU QUE TEM A FUNÇÃO SA_REP
USANDO SET OPERATORS.

2) MOSTRE OS FUNCIONARIOS (LAST_NAME E SALARY) QUE TRABALHAM
NOS DEPARTAMENTOS: 90, 10 E 20 NESSA ORDEM.


3) MOSTRE TODOS OS DEPARTAMENTO DA EMPRESA (DEPARTMENT_ID E
DEPARTMENT_NAME) QUE NÃO TEM FUNCIONARIOS 'ST_CLERK'
USANDO SET OPERATORS.