/*
1) USANDO O USUARIO SYSDBA, CRIE UM DIRETORIO "TMP"
QUE APONTE PARA A PASTA 'C:\TEMP'
*/
CREATE DIRECTORY TMP AS 'C:\temp';

GRANT READ, WRITE ON DIRECTORY TMP TO ORA1;

/*
2) LOCALIZE A PASTA C:\TEMP NO WINDOWS E CRIE NELA
UM ARQUIVO COM O NOME "ORAEMP.CSV" E INCLUA NELE O
SEGUINTE CONTEÚDO:

FIRST_NAME,LAST_NAME,CITY,SALARY
IGOR,RIBEIRO,UBERABA,500
RENATO,SILVA,SAO PAULO,2500
GABRIEL,COSTA,SAO PAULO,12000
FATIMA,DIAS,BELO HORIZONTE, 7000

*/

/*
3) CRIE UM TABELA EXTERNA QUE LEIA E APRESENTE O
CONTEÚDO DO ARQUIVO 'ORAEMP.CSV'.
*/

--DROP TABLE ORAEMP;
CREATE TABLE ORAEMP (
       FIRST_NAME CHAR(20),
       LAST_NAME  CHAR(20),
       CITY       CHAR(20),
       SALARY     CHAR(20))
ORGANIZATION EXTERNAL (TYPE ORACLE_LOADER DEFAULT
             DIRECTORY TMP ACCESS PARAMETERS (
                           RECORDS DELIMITED BY NEWLINE
                           SKIP 1
                           FIELDS TERMINATED BY ',' (
                                  FIRST_NAME CHAR(20),
                                  LAST_NAME  CHAR(20),
                                  CITY       CHAR(20),
                                  SALARY     CHAR(20)))
             LOCATION('ORAEMP.csv'));
SELECT * FROM ORAEMP;             
















