1) MONTE UM RELATÓRIO COMPLETO SOBRE OS EMPREGADOS PARA O
DEPARTAMENTO DE RH:
DEPARTMENT_ID, DEPARTMENT_NAME, CITY, COUNTRY_NAME, 
REGION_NAME, EMPLOYEE_ID, FIRST_NAME, JOB_TITLE, SALARY
OBS: - COLOQUE NOME(ALIAS) PARA AS COLUNAS
     - TODOS OS DEPARTAMENTO DEVEM SER EXIBIDOS


2) MONTE UM RELATÓRIO MOSTRANDO A QUANDIDADE DE EMPREGADOS
POR DEPARTAMENTO E A SOMA DOS SALARIOS:

NOME DO DEPARTAMENTO | QTD.FUNCIONARIO | SOMA SALARIOS
FINANCE              | 5               | R$ 21.000,00

