1) CRIE A TABELA ABAIXO:

CREATE TABLE CURSO (
   COD_CURSO  NUMBER(10) CONSTRAINT PK_CURSO
                                    PRIMARY KEY,
   NOM_CURSO  VARCHAR2(30 CHAR) NOT NULL,
   DAT_INICIO DATE,
   DAT_FIM    DATE,
   CONSTRAINT CK_DATA CHECK(DAT_FIM > DAT_INICIO));

A) QUAIS CONSTRAINT FORAM UTILIZADAS?
B) QUAIS FORAM DEFINIDAS NO NIVEL DA COLUNA?
C) QUAIS FORAM DEFINIDAS NO NIVEL DA TABELA?
D) A CONSTRAINT CK_DATA PODERIA SER DEFINIDA 
   NO NIVEL DA COLUNA?   

   
2) CRIE A TABELA ABAIXO:
   
   CREATE TABLE ALUNO (
      COD_ALUNO NUMBER(10) CONSTRAINT PK_ALUNO
                                      PRIMARY KEY,
      NUM_MATRICULA VARCHAR2(10 CHAR) NOT NULL,
      NOM_ALUNO     VARCHAR2(50 CHAR) NOT NULL,
 	  DAT_MATRICULA DATE    DEFAULT SYSDATE,
	  NOM_CIDADE    VARCHAR2(40 CHAR) DEFAULT
	                                  'SÃO PAULO',
      NUM_IDADE NUMBER(3) CONSTRAINT CK_MAIOR 
	                      CHECK(NUM_IDADE >= 18),
      DES_EMAIL VARCHAR2(255) CONSTRAINT UK_EMAIL
	                      UNIQUE,
      COD_CURSO NUMBER(10) CONSTRAINT FK_CURSO
                          REFERENCES CURSO(COD_CURSO)
    );						  

   CREATE TABLE ALUNO (
      COD_ALUNO NUMBER(10) CONSTRAINT PK_ALUNO
                                      PRIMARY KEY,
      NUM_MATRICULA VARCHAR2(10 CHAR) NOT NULL,
      NOM_ALUNO     VARCHAR2(50 CHAR) NOT NULL,
 	  DAT_MATRICULA DATE    DEFAULT SYSDATE,
	  NOM_CIDADE    VARCHAR2(40 CHAR) DEFAULT
	                                  'SÃO PAULO',
      NUM_IDADE NUMBER(3) CONSTRAINT CK_MAIOR 
	                      CHECK(NUM_IDADE >= 18),
      DES_EMAIL VARCHAR2(255) CONSTRAINT UK_EMAIL
	                      UNIQUE,
      COD_CURSO NUMBER(10),
	  CONSTRAINT FK_CURSO FOREIGN KEY (COD_CURSO)
                          REFERENCES CURSO(COD_CURSO)
    );						  


A) QUAIS CONSTRAINT FORAM UTILIZADAS?
B) QUAIS FORAM DEFINIDAS NO NIVEL DA COLUNA?
C) QUAIS FORAM DEFINIDAS NO NIVEL DA TABELA?
D) A CONSTRAINT FK_CURSO PODERIA SER DEFINIDA 
   NO NIVEL DA TABELA?


3) DROP A TABELA ALUNO E RECRIE-A DECLARANDO
A FK_CURSO NO NIVEL DA TABELA

4) ALTERE A TABELA ALUNO PARA VALIDAR O EMAIL,
   PERMITINDO APENAS EMAIL COM LETRAS MINUSCULA
   DÊ O NOME PARA CONSTRAINT DE CK_EMAIL_MIN

   ALTER TABLE ALUNO ADD (
      CONSTRAINT CK_EMAIL_MIN
  	     CHECK(LOWER(DES_EMAIL) = DES_EMAIL));
   
5) ALTERE A TABELA ALUNO ADICIONADO A COLUNA 
   "UNIDADE" DO TIPO VARCHAR2(20 CHAR) COM VALOR
   DEFAULT 'CENTRO'.
   
   ALTER TABLE ALUNO ADD (
      UNIDADE VARCHAR2(20 CHAR) DEFAULT 'CENTRO');
   
6) ALTERE A TABELA ALUNO AUMENTANDO O TAMANHO
   DE UNIDADE DE 20 PARA 40
   
   ALTER TABLE ALUNO MODIFY (
      UNIDADE VARCHAR2(40 CHAR));
  
7) ALTERE NOVAMENTE A TABELA ALUNO SETANDO A COLUNA
   UNIDADE PARA UNUSED E EM SEGUIDA DROP TODAS AS
   UNUSED COLUMNS
   
   ALTER TABLE ALUNO 
      SET UNUSED (UNIDADE);
	  
   ALTER TABLE ALUNO
      DROP UNUSED COLUMNS;





   
   
   
   
   
   
   
   
   
   