1) EXECUTE O SEGUINTE COMANDO NO SQLDEVELOPER:

CREATE TABLE EMP_TEMP (
     EMP_ID NUMBER(10) PRIMARY KEY,
	 EMP_NAME VARCHAR2(50 CHAR) NOT NULL,
	 EMP_SAL NUMBER(8,2) NOT NULL);
	 
2) CRIE UM COMANDO DE INSERÇÃO DINÂMICO NA TABELA ACIMA.
   TESTE O SCRIPT INSERINDO 3 FUNCIONARIOS

3) INSIRA, DE UMA ÚNICA VEZ, OS FUNCIONARIOS DA TABELA
EMPLOYEES QUE TRABALHAM NOS DEPARTAMENTOS 50 E 60.
OBS.: SÓ AS 3 COLUNA REQUERIDAS	 

4) ATUALIZE O SALARIO DOS FUNCIONARIOS COM UM AUMENTO DE
10%.

5) APAGUE DA TABELA TODOS OS FUNCIONARIOS QUE TEM SALARIO
ACIMA DE 6800.00

6) CONVERTA O NOME DE TODOS OS FUNCIONARIOS PARA LETRAS
MAÚSCULAS.







