1) O DEPARTAMENTO DE RH PRECISA MARCAR O EXAME MÉDICO
DOS FUNCIONARIOS. TODO FUNCIONARIO PRECISA SER SUBMETIDO
A UM EXAME NA PRIMEIRA SEGUNDA-FEIRA APÓS 6 MESES DE
CONTRATAÇÃO
MONTE UM RELATÓRIO QUE MOSTRE O ID, NOME E SOBRENOME,
DATA DE CONTRATAÇÃO E DATA DO EXAME.
(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, HIRE_DATE, EXAME)

2) A CADA 2 ANOS NO PRIMEIRO DOMINGO DO MÊS DE OUTUBRO
ACONTECE AS ELEIÇÕES EM TODO PAÍS. MONTE UM SCRIPT QUE
MOSTRE, DE ACORDO COM A DATA DE CONTRATAÇÃO DO
FUNCIONARIO, SE HOUVE ELEIÇÃO OU NÃO, COMO NO EXEMPLO:

NOME E SOBRENOME | ANO CONTRATAÇÃO | ELEIÇÃO?
IGOR RIBEIRO     |      2016       | SIM, EM: 02 de Outubro
MARCELO SILAVA   |      2003       | NÃO TEVE ELEIÇÃO

