/*
1) CRIE UMA GTT COM AS COLUNAS
       COD_COMPRA - NUMBER(10)
	   NOM_CLIENTE - VARCHAR2(30 CHAR)
   LIMPE OS DADOS DA TABELA A CADA COMMIT.
*/   

CREATE GLOBAL TEMPORARY TABLE COMPRA (
       COD_COMPRA NUMBER(10),
	   NOM_CLIENTE VARCHAR2(30 CHAR))
ON COMMIT DELETE ROWS;
DESC COMPRA;
   
/*
2) INSIRA NA TABELA OS SEGUINTES DADOS:
     CODIGO  | CLIENTE
        1    | LUCIANO BARROS
        2    | VICTOR HUGO
        3    | TAIS SILVA
*/

INSERT INTO COMPRA VALUES (1, 'LUCIANO BARROS');
INSERT INTO COMPRA VALUES (2, 'VICTOR HUGO');
INSERT INTO COMPRA VALUES (3, 'TAIS SILVA');


/*
3) DE UM SELECT E VERIFIQUE OS DADOS INSERIDOS.
*/

SELECT * FROM COMPRA;

/*
4) COMMITE OS DADOS E VERIFIQUE O CONTEÚDO DA
   TABELA NOVAMENTE. O QUE ACONTECEU?		
*/   

COMMIT;
SELECT * FROM COMPRA;

