--CRIAR UM NOVO USUARIO
CREATE USER IGOR IDENTIFIED BY 12345678;

--DAR PERMISSÃO DE CONEXÃO PARA O USUARIO
GRANT CREATE SESSION TO IGOR;

--PERMISSÕES COMUNS
GRANT CREATE TABLE, CREATE SEQUENCE, 
      CREATE VIEW, CREATE SYNONYM TO IGOR;
      
--GRANT DE SELECT NA TABELA EMPLOYEES DO USUARIO ORA41
GRANT SELECT ON ORA41.EMPLOYEES TO IGOR;      

--CRIAR A ROLE E PASSAR AS PERMISSÕES
CREATE ROLE RL_PROGRAMADOR;

GRANT CREATE TABLE, CREATE SEQUENCE, 
      CREATE VIEW, CREATE SYNONYM TO RL_PROGRAMADOR;
      
GRANT RL_PROGRAMADOR TO IGOR;      

REVOKE CREATE TABLE, CREATE SEQUENCE, 
      CREATE VIEW, CREATE SYNONYM FROM IGOR;
      
ALTER USER IGOR  
   QUOTA UNLIMITED ON USERS;


















