/*
1) CRIE A SEQUENCE SEQ_COD_CURSO, COM INCREMENTO
DE 1 EM 1 E COM VALOR INICIAL 97000;
*/

CREATE SEQUENCE SEQ_COD_CURSO
       INCREMENT BY 1
       START WITH 97000;

/*
2) ALTERE A TABELA CURSO, COLOCANDO A SEQUENCE
CRIADA NO ITEM 1 COMO VALOR DEFAULT PARA A COLUNA
"COD_CURSO" - "SEQ_COD_CURSO.NEXTVAL"
*/

   ALTER TABLE CURSO MODIFY (
      COD_CURSO DEFAULT SEQ_COD_CURSO.NEXTVAL);

/*
3) CRIE A SEQUENCE SEQ_COD_ALUNO, COM INCREMENTO
DE 1 EM 1 E VALOR INICIAL 1;
*/

   CREATE SEQUENCE SEQ_COD_ALUNO;

/*
4) ALTERE A TABELA ALUNO, COLOCANDO A SEQUENCE
CRIADA NO ITEM 3 COM VALOR DEFAULT PARA A COLUNA
"COD_ALUNO" - "SEQ_COD_ALUNO.NEXTVAL"
*/

  ALTER TABLE ALUNO MODIFY (
     COD_ALUNO DEFAULT SEQ_COD_ALUNO.NEXTVAL);

/*
5) INSIRA UM CURSO QUALQUER E EM SEGUIDA INSIRA
2 ALUNOS NESSE CURSO. DE UM SELECT NA TABELA E VEJA
O VALOR GERADO PARA AS COLUNAS "COD_"
*/

DESC CURSO;
INSERT INTO CURSO (NOM_CURSO, DAT_INICIO, DAT_FIM)
           VALUES ('SQL', SYSDATE, SYSDATE + 30);
SELECT * FROM CURSO;

DESC ALUNO;
INSERT INTO ALUNO (NUM_MATRICULA, NOM_ALUNO, DAT_MATRICULA, NOM_CIDADE,
                   NUM_IDADE, DES_EMAIL, COD_CURSO)
           VALUES ('MAT_001', 'JOSÉ', SYSDATE, DEFAULT, 20,
                   'jose@hotmail.com', 97000);
SELECT * FROM ALUNO;

/*
6) CRIE UM SINÔNIMO PARA ORA41.EMPLOYEES

*/
SELECT * FROM ORA41.EMPLOYEES;

CREATE SYNONYM ORA41EMP FOR ORA41.EMPLOYEES;

SELECT * FROM ORA41EMP;

/*
7) CRIE 2 INDICES PARA A COLUNA FIRST_NAME DA TABELA
   EMPLOYEES UM NORMAL E OUTRO COM A FUNÇÃO UPPER
*/

CREATE INDEX IDX_FNAME ON EMPLOYEES(FIRST_NAME);
CREATE INDEX IDX_FNAMEU ON EMPLOYEES(UPPER(FIRST_NAME));

SELECT * FROM EMPLOYEES
  WHERE UPPER(FIRST_NAME) LIKE 'KEVIN%';


