TRUNCATE TABLE NOTAS; 
ALTER TABLE NOTAS DISABLE CONSTRAINT FK_ALUNO;
TRUNCATE TABLE ALUNO;
ALTER TABLE NOTAS ENABLE CONSTRAINT FK_ALUNO;
/
DESC ALUNO;
EXEC SP_INSERE_ALUNO('IGOR THOMAZ RIBEIRO', 'thigor@gmail.com');
EXEC SP_INSERE_ALUNO('VICTOR HUGO', 'hgvictor@gmail.com');
/
SELECT * FROM ALUNO;
/
INSERT INTO NOTAS VALUES (DEFAULT, 41, 201801, 7.0, 8.0, 9.0, 9.0, 0);
INSERT INTO NOTAS VALUES (DEFAULT, 41, 201802, 7.5, 8.0, 9.0, 8.0, 0);
INSERT INTO NOTAS VALUES (DEFAULT, 42, 201801, 8.0, 8.0, 9.0, 7.0, 0);
INSERT INTO NOTAS VALUES (DEFAULT, 42, 201802, 8.5, 8.0, 9.0, 6.0, 0);
/
SELECT * FROM NOTAS;
/
BEGIN
    --PKG_TREINAMENTO.SP_CARREGA_NOTAS;
    UPDATE NOTAS SET VL_MEDIA = PKG_TREINAMENTO.FC_CALCULA_MEDIA(CD_ALUNO, NM_SEMESTRE);
END;
/
CREATE TRIGGER TG_RECARREGA_NOTAS
  AFTER INSERT OR UPDATE OR DELETE ON NOTAS
    CALL PKG_TREINAMENTO.SP_CARREGA_NOTAS
/
SELECT * FROM NOTAS;
/
--DEPOIS DA TRIGGER CRIADA
UPDATE NOTAS SET VL_NOTA1 = VL_NOTA1 - 1.5;
/
UPDATE NOTAS SET VL_MEDIA = PKG_TREINAMENTO.FC_CALCULA_MEDIA(CD_ALUNO, NM_SEMESTRE);
/

    